sudo: required
services :
  - docker

before_install:
  - docker build -t hassane-ariss/docker-react2 -f Dockerfile.dev .

script:
  - docker run hassane-ariss/docker-react2 npm run test -- --coverage
